[package]
name = "tm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.26"
chrono-tz = "0.8.3"
clap = { version = "4.4.6", features = ["derive"] }
home = "0.5.5"
rusqlite = "0.29.0"
